Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_13_BE, pull requests merged in 2024-07, with the labels that each got.

#21 [MSA] server-config 설정 파일 #20
  server-config/build.gradle
  server-config/gradle/wrapper/gradle-wrapper.jar
  server-config/gradle/wrapper/gradle-wrapper.properties
  server-config/gradlew
  server-config/gradlew.bat
  server-config/settings.gradle
Labels: feature

#26 [MSA] Jenkins 적용
  server-config/Dockerfile
  server-config/Jenkinsfile
  server-config/build.gradle
  server-eureka/Dockerfile
  server-eureka/Jenkinsfile
  server-eureka/build.gradle
  server-eureka/src/main/resources/application.yml
  service-chat/Dockerfile
  service-chat/Jenkinsfile
  service-chat/build.gradle
  service-chat/src/main/resources/application.yml
  service-chat/src/test/java/com/team13/servicechat/ServiceChatApplicationTests.java
  service-post/Dockerfile
  service-post/Jenkinsfile
  service-post/build.gradle
  service-post/src/main/resources/application.yml
  service-post/src/test/java/com/team13/servicepost/ServicePostApplicationTests.java
  service-recipe/Dockerfile
  service-recipe/Jenkinsfile
  service-recipe/build.gradle
  service-recipe/src/main/resources/application.yml
  service-recipe/src/test/java/com/team13/servicerecipe/ServiceRecipeApplicationTests.java
  service-user/Dockerfile
  service-user/Jenkinsfile
  service-user/build.gradle
  service-user/src/main/resources/application.yml
  service-user/src/test/java/com/team13/serviceuser/ServiceUserApplicationTests.java
Labels: feature

#28 [MSA] API Gateway 적용
  .github/pull_request_template.md
  server-apigateway/build.gradle
  server-apigateway/src/main/java/com/team13/ServerApiGatewayApplication.java
  server-apigateway/src/main/resources/application.yml
  server-eureka/src/main/resources/application.yml
  settings.gradle
Labels: feature

#33 [Infra] Jenkins 브런치 디텍팅 문제
  server-config/Dockerfile
  server-config/Jenkinsfile
  server-eureka/Jenkinsfile
  service-chat/Jenkinsfile
  service-post/Jenkinsfile
  service-recipe/Jenkinsfile
  service-user/Jenkinsfile
Labels: bug

#34 [MSA] server-gateway
  server-eureka/src/main/resources/application.yml
  server-gateway/Dockerfile
  server-gateway/Jenkinsfile
  server-gateway/build.gradle
  server-gateway/gradle/wrapper/gradle-wrapper.jar
  server-gateway/gradle/wrapper/gradle-wrapper.properties
  server-gateway/gradlew
  server-gateway/gradlew.bat
  server-gateway/settings.gradle
  server-gateway/src/main/java/com/team13/servergateway/ServerGatewayApplication.java
  server-gateway/src/main/resources/application.yml
  settings.gradle
Labels: refactoring

#37 [JWT] JWT 기능 구현
  server-gateway/build.gradle
  server-gateway/src/main/java/com/team13/servergateway/filter/JwtAuthFilter.java
  server-gateway/src/main/java/com/team13/servergateway/util/RouterValidator.java
  server-gateway/src/main/resources/application.yml
  service-user/build.gradle
  service-user/src/main/java/com/team13/serviceuser/controller/IndexController.java
  service-user/src/main/java/com/team13/serviceuser/service/SignInService.java
  service-user/src/test/java/com/team13/serviceuser/controller/IndexControllerTest.java
Labels: feature

#38 [MSA] 배포 환경 구성
  server-gateway/Jenkinsfile
  server-gateway/src/main/resources/application.yml
Labels: feature
