Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_13_BE, pull requests merged in 2025-01, with the labels that each got.

#72 feat: API 게이트웨이 JWT 쿠키 로직 변경
  server-gateway/build.gradle
  server-gateway/src/main/java/com/team13/servergateway/filter/JwtAuthFilter.java
  server-gateway/src/main/java/com/team13/servergateway/util/cookie/Cookie.java
  server-gateway/src/main/java/com/team13/servergateway/util/cookie/CookieParser.java
  service-user/src/main/java/com/team13/serviceuser/controller/IndexController.java
Labels: feature

#73 [마이페이지] GatewayFilter JWT로 GET info정보
  server-gateway/src/main/java/com/team13/servergateway/filter/JwtAuthFilter.java
  server-gateway/src/main/java/com/team13/servergateway/util/RouterValidator.java
  server-gateway/src/main/resources/application.yml
  service-user/src/main/java/com/team13/serviceuser/controller/MypageController.java
  service-user/src/main/java/com/team13/serviceuser/controller/SignController.java
  service-user/src/main/java/com/team13/serviceuser/service/SignInService.java
  service-user/src/main/resources/application.yml
Labels: feature

#74 fix: 테스트 코드 관련 오류 수정
  service-user/src/test/java/com/team13/serviceuser/controller/IndexControllerTest.java
Labels: feature

#75 [레시피]
  server-gateway/src/main/java/com/team13/servergateway/util/RouterValidator.java
  service-recipe/src/main/java/com/team13/servicerecipe/controller/RecipeController.java
  service-recipe/src/main/java/com/team13/servicerecipe/feign/UserServiceClient.java
  service-user/src/main/java/com/team13/serviceuser/controller/MypageController.java
  service-user/src/main/java/com/team13/serviceuser/controller/SignController.java
  service-user/src/main/java/com/team13/serviceuser/controller/UserController.java
  service-user/src/main/java/com/team13/serviceuser/feign/RecipeServiceClient.java
Labels: refactoring

#79 fix: 쿠키값을 가져오는 로직 변경
  server-gateway/src/main/java/com/team13/servergateway/util/RouterValidator.java
  server-gateway/src/main/java/com/team13/servergateway/util/cookie/CookieParser.java
Labels: bug
